property_model_training:
    n_data: 100000
    num_epochs: 500
    batch_size: 10000
    n_onehot: 5
    nbr_fea_len: 4
    learning_rate: 0.01
    max_size: 20
    random_split: True
    noise_factor: 0.2
    transfer_learn: True
    use_pretrained: True

inverter:
    max_size: 20
    min_size: 5
    starting_size: 20
    sig_strength: 1
    start_from: "random"
    n_iter: 15000
    mini_hpo:
        method: False
        n_comb: 0
        n_starts: 5
        n_iter: 1000
        stop_chem: 0.9
        stop_loss: 1
    inv_r: 0.1
    n_onehot: 5
    l_loss: 10
    l_const: 1
    stop_chem: 0.3
    stop_loss: 0.9
    show_losses: False
    max_attempts: 1
