property_model_training:
    n_data: 690
    num_epochs: 500
    batch_size: 230
    n_onehot: 5
    nbr_fea_len: 4
    learning_rate: 0.01
    max_size: 10
    random_split: True
    noise_factor: 0.2
    transfer_learn: False
    use_pretrained: True

inverter:
    max_size: 10
    starting_size: 10 
    sig_strength: 1
    start_from: "random"
    n_iter: 30000
     mini_hpo:
        n_comb: 0
        n_starts: 2000
        n_iter: 20
        stop_chem: 0.3
        stop_loss: 1
    inv_r: 0.001
    n_onehot: 5
    l_loss: 1
    l_const: 1
    l_fea: 0
    l_adj: 0
    stop_chem: 0.1
    stop_loss: 0.3
    show_losses: False
    max_attempts: 3