#!/usr/bin/env python3

import argparse
from didgen import generate

def read_options():

    parser = argparse.ArgumentParser()
    parser.add_argument("-p","--target-property",dest="property",type=float, default=6, help="Requested HOMO-LUMO gap")
    parser.add_argument("-n","--number-of-gen",dest="n",type=int, default=1, help="Number of requested molecules")
    parser.add_argument("-c","--config",dest="config",type=str, default="config.yml", help="Config file location")
    parser.add_argument("-o","--output",dest="output",type=str, default="out_gen", help="Output folder")
    
    args = parser.parse_args()

    return args

def main():

    args = read_options()

    generate(args.property, args.n, args.output, args.config)

main()
